// <auto-generated />
using System;
using AgentForge.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgentForge.Persistence.Migrations
{
    [DbContext(typeof(AgentForgeDbContext))]
    [Migration("20260811234443_DurableDecoderGovernance")]
    partial class DurableDecoderGovernance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AgentForge.Persistence.Entities.AgentIdentityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowFallback")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataLocality")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultWorkspace")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Expertise")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearningMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxChildConcurrency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxChildDepth")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MaxChildTotalTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxChildren")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MaxInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MaxOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxToolInvocations")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTurns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxWallClockSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemoryRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MemoryScope")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mission")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("MutableSkillScope")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("NetworkPosture")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrimaryProviderProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseStyle")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillGrantsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolGrantsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryProviderProfileId");

                    b.HasIndex("InstallationId", "Name")
                        .IsUnique();

                    b.ToTable("agent_identities", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.AgentLoopSnapshotEntity", b =>
                {
                    b.Property<Guid>("LoopId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<long>("AgentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CausationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CompletionPending")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveNoProgress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("InitialStateHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastProgressEvidenceHash")
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximumConsecutiveNoProgress")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MaximumInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MaximumOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumStructuredRepairs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumToolCalls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumTurns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumWallClockSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousSnapshotHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepEvidenceHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<int>("StructuredRepairCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Turn")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UsedInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UsedOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsedToolCalls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsedWallClockSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoopId", "Sequence");

                    b.HasIndex("AgentId");

                    b.HasIndex("InstallationId", "AgentId", "UpdatedAtUtcTicks");

                    b.HasIndex("InstallationId", "IdempotencyKey", "Sequence")
                        .IsUnique();

                    b.ToTable("agent_loop_snapshots", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.ArtifactEntity", b =>
                {
                    b.Property<string>("ContentHash")
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("ContentHash");

                    b.ToTable("artifacts", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CausationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorClassification")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("Sequence")
                        .IsUnique();

                    b.HasIndex("InstallationId", "Sequence");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.CapabilityApprovalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<long>("AgentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ConsumedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecidedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("InstallationVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParametersHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<long?>("RevokedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RiskClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolDescriptorHash")
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolVersion")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkspaceHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("InstallationId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("InstallationId", "AgentId", "RequestHash", "CreatedAtUtcTicks");

                    b.ToTable("capability_approvals", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.ChannelDeliveryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("InstallationId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("InstallationId", "AgentId", "Channel", "State", "UpdatedAtUtcTicks");

                    b.ToTable("channel_deliveries", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.ChannelIdentityBindingEntity", b =>
                {
                    b.Property<string>("Channel")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSenderId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Channel", "AccountId", "ExternalSenderId");

                    b.HasIndex("AgentId");

                    b.HasIndex("InstallationId");

                    b.ToTable("channel_identity_bindings", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.ChannelInboundMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalMessageId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("ReceivedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("Channel", "AccountId", "ExternalMessageId")
                        .IsUnique();

                    b.HasIndex("InstallationId", "AgentId", "OrderKey");

                    b.ToTable("channel_inbound_messages", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.CodingSessionSnapshotEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CausationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousSnapshotHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId", "Version");

                    b.HasIndex("InstallationId", "AgentId", "UpdatedAtUtcTicks");

                    b.HasIndex("InstallationId", "IdempotencyKey", "Version")
                        .IsUnique();

                    b.ToTable("coding_session_snapshots", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.DecoderActiveVersionEntity", b =>
                {
                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecoderId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("InstallationId", "DecoderId");

                    b.ToTable("decoder_active_versions", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.DecoderProposalSnapshotEntity", b =>
                {
                    b.Property<Guid>("ProposalId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaselineHash")
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("DecoderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousSnapshotHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProposalId", "Version");

                    b.HasIndex("InstallationId", "DecoderId", "UpdatedAtUtcTicks");

                    b.ToTable("decoder_proposal_snapshots", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.DelegationGrantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CausationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChildAgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GrantHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("GrantJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("IssuedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ParentAgentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParentTaskId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChildAgentId");

                    b.HasIndex("ParentAgentId");

                    b.HasIndex("InstallationId", "ParentTaskId", "IssuedAtUtcTicks");

                    b.ToTable("delegation_grants", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.InstallationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryReason")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("installations", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.LocalAdministratorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretStore")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Verifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifierAlgorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifierSalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("VerifierWorkFactor")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActorId")
                        .IsUnique();

                    b.HasIndex("InstallationId")
                        .IsUnique();

                    b.ToTable("local_administrators", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.MemoryEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CausationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("RedactionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceEvidenceHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUri")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("InstallationId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("InstallationId", "AgentId", "ScopeId", "Kind", "ExpiresAtUtcTicks");

                    b.ToTable("memory_entries", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.ModelBudgetLedgerEntity", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ActiveRuns")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AgentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CompletedRuns")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ConsumedEvents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ConsumedInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ConsumedOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ConsumedToolCalls")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ConsumedWallClockSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservedEvents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReservedInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReservedOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservedToolCalls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservedWallClockSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("AgentId");

                    b.HasIndex("InstallationId", "AgentId")
                        .IsUnique();

                    b.ToTable("model_budget_ledgers", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.ModelProviderHealthEntity", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CausationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LastAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LastRunId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RetryAfterUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfileId");

                    b.HasIndex("LastAttemptId");

                    b.HasIndex("LastRunId");

                    b.HasIndex("InstallationId", "UpdatedAtUtcTicks");

                    b.ToTable("model_provider_health", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.ModelRunAttemptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventStreamHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishReason")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFallback")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRetryable")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastEventSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanEvidenceHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProviderProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProviderVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequiredCapabilitiesJson")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservedEvents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReservedInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReservedOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservedToolCalls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservedWallClockSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectionEvidenceHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StartedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("UsedInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UsedOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsedToolCalls")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProviderProfileId");

                    b.HasIndex("RunId", "Sequence")
                        .IsUnique();

                    b.ToTable("model_run_attempts", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.ModelRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("AdmissionRequestHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<long>("AgentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttemptedProfileIdsJson")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CausationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsumedWallClockSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContextPreparationPolicy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ContextRedactionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventStreamHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishReason")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthEvidenceHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("InstallationVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFallback")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastEventSequence")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LeaseAcquiredAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LeaseExpiresAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LeaseHeartbeatAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseTokenHash")
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximumAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanEvidenceHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreparedInputHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProviderProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProviderVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredCapabilitiesJson")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservedEvents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReservedInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReservedOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservedToolCalls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservedWallClockSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectionEvidenceHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("UsedInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UsedOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsedToolCalls")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ProviderProfileId");

                    b.HasIndex("InstallationId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("InstallationId", "AgentId", "CreatedAtUtcTicks");

                    b.ToTable("model_runs", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.OrchestrationTaskSnapshotEntity", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CausationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousSnapshotHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskId", "Version");

                    b.HasIndex("AgentId");

                    b.HasIndex("InstallationId", "AgentId", "UpdatedAtUtcTicks");

                    b.HasIndex("InstallationId", "IdempotencyKey", "Version")
                        .IsUnique();

                    b.ToTable("orchestration_task_snapshots", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt", "OccurredAt");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.ProviderProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceSource")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Images")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretStore")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Streaming")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TextGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ToolCalls")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId", "Name")
                        .IsUnique();

                    b.ToTable("provider_profiles", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.ScheduleSnapshotEntity", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CausationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("NextDueAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NextScheduledAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviousSnapshotHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("ScheduleId", "Version");

                    b.HasIndex("AgentId");

                    b.HasIndex("State", "NextDueAtUtcTicks");

                    b.HasIndex("InstallationId", "IdempotencyKey", "Version")
                        .IsUnique();

                    b.ToTable("schedule_snapshots", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.SerialCaptureEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactContentHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("CaptureJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhysicalDeviceId")
                        .IsRequired()
                        .HasMaxLength(78)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StreamHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ArtifactContentHash");

                    b.HasIndex("InstallationId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("InstallationId", "PhysicalDeviceId", "StartedAtUtcTicks");

                    b.ToTable("serial_captures", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.SetupProfileSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactContentHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ArtifactCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("ArtifactLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtifactMediaType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProfileVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactContentHash");

                    b.HasIndex("InstallationId", "ProfileVersion", "Kind");

                    b.ToTable("setup_profile_snapshots", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.SkillActiveVersionEntity", b =>
                {
                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("InstallationId", "SkillId");

                    b.HasIndex("InstallationId", "SkillId", "Version");

                    b.ToTable("skill_active_versions", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.SkillProposalSnapshotEntity", b =>
                {
                    b.Property<Guid>("ProposalId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousSnapshotHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposalJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProposalId", "Version");

                    b.HasIndex("InstallationId", "SkillId", "UpdatedAtUtcTicks");

                    b.ToTable("skill_proposal_snapshots", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.SkillRunSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CausationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("skill_run_snapshots", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.SkillVersionEntity", b =>
                {
                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactContentHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptorJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("InstallationId", "SkillId", "Version");

                    b.HasIndex("ArtifactContentHash");

                    b.HasIndex("InstallationId", "SkillId", "Status");

                    b.ToTable("skill_versions", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.ToolInvocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<long>("AgentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ApprovalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CausationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("InstallationVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParametersHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardErrorHash")
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<int>("StandardErrorLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StandardOutputHash")
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<int>("StandardOutputLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolDescriptorHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkspaceHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ApprovalId");

                    b.HasIndex("InstallationId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("InstallationId", "AgentId", "CreatedAtUtcTicks");

                    b.ToTable("tool_invocations", (string)null);
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.AgentIdentityEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentForge.Persistence.Entities.ProviderProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("PrimaryProviderProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.AgentLoopSnapshotEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.AgentIdentityEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.CapabilityApprovalEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.AgentIdentityEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.ChannelDeliveryEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.AgentIdentityEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.ChannelIdentityBindingEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.AgentIdentityEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.ChannelInboundMessageEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.AgentIdentityEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.CodingSessionSnapshotEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.DecoderActiveVersionEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.DecoderProposalSnapshotEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.DelegationGrantEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.AgentIdentityEntity", null)
                        .WithMany()
                        .HasForeignKey("ChildAgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentForge.Persistence.Entities.AgentIdentityEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentAgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.LocalAdministratorEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.MemoryEntryEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.AgentIdentityEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.ModelBudgetLedgerEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.AgentIdentityEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.ModelProviderHealthEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentForge.Persistence.Entities.ModelRunAttemptEntity", null)
                        .WithMany()
                        .HasForeignKey("LastAttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentForge.Persistence.Entities.ModelRunEntity", null)
                        .WithMany()
                        .HasForeignKey("LastRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentForge.Persistence.Entities.ProviderProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.ModelRunAttemptEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.ProviderProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("ProviderProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentForge.Persistence.Entities.ModelRunEntity", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.ModelRunEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.AgentIdentityEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentForge.Persistence.Entities.ProviderProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("ProviderProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.OrchestrationTaskSnapshotEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.AgentIdentityEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.ProviderProfileEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.ScheduleSnapshotEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.AgentIdentityEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.SerialCaptureEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.AgentIdentityEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentForge.Persistence.Entities.ArtifactEntity", null)
                        .WithMany()
                        .HasForeignKey("ArtifactContentHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.SetupProfileSnapshotEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.ArtifactEntity", null)
                        .WithMany()
                        .HasForeignKey("ArtifactContentHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.SkillActiveVersionEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.SkillVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId", "SkillId", "Version")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.SkillProposalSnapshotEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.SkillRunSnapshotEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.SkillVersionEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.ArtifactEntity", null)
                        .WithMany()
                        .HasForeignKey("ArtifactContentHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentForge.Persistence.Entities.ToolInvocationEntity", b =>
                {
                    b.HasOne("AgentForge.Persistence.Entities.AgentIdentityEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentForge.Persistence.Entities.CapabilityApprovalEntity", null)
                        .WithMany()
                        .HasForeignKey("ApprovalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AgentForge.Persistence.Entities.InstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
