<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AgentForge.Abstractions\AgentForge.Abstractions.csproj" />
    <ProjectReference Include="..\AgentForge.Domain\AgentForge.Domain.csproj" />
  </ItemGroup>

</Project>
